In [5]:
import pandas as pd
from pathlib import Path

project_folder = Path.cwd().parent if Path.cwd().name == "notebooks" else Path.cwd()

df = pd.read_csv(project_folder / "data" / "dirty" / "yrbs_dirty_9vars.csv")

df.head(30)

,row_id,age,sex,grade,social_media_use,mental_health_not_good,sleep_hours,bmipct,height_orig,weight_orig
0,1,NaN,NaN,NaN,6.0,1.0,3.0,97.08,505,180
1,2,NaN,NaN,NaN,4.0,3.0,5.0,NaN,N N,233
2,3,NaN,NaN,NaN,8.0,2.0,1.0,92.26,506,165
3,4,NaN,NaN,NaN,8.0,3.0,4.0,NaN,N N,105
4,5,NaN,NaN,NaN,6.0,3.0,3.0,7.57,601,125
5,6,NaN,NaN,NaN,8.0,NaN,2.0,68.89,511,160
6,7,NaN,NaN,NaN,8.0,3.0,2.0,60.48,600,165
7,8,NaN,NaN,NaN,6.0,2.0,1.0,97.53,500,162
8,9,NaN,NaN,NaN,6.0,3.0,1.0,76.45,505,135
9,10,NaN,NaN,NaN,6.0,1.0,2.0,34.79,504,117
10,11,NaN,NaN,NaN,1.0,1.0,7.0,64.23,507,140
11,12,NaN,NaN,NaN,6.0,1.0,4.0,95.81,502,159
12,13,NaN,NaN,NaN,6.0,1.0,4.0,82.18,506,145
13,14,NaN,NaN,NaN,6.0,1.0,2.0,99.42,504,300
14,15,NaN,NaN,NaN,7.0,1.0,5.0,86.65,509,163
15,16,NaN,NaN,NaN,8.0,4.0,2.0,98.75,506,215
16,17,NaN,NaN,NaN,8.0,1.0,3.0,99.19,602,270
17,18,NaN,NaN,NaN,3.0,3.0,5.0,3.87,604,150
18,19,NaN,NaN,NaN,6.0,3.0,5.0,17.75,505,110
19,20,NaN,NaN,NaN,2.0,3.0,1.0,NaN,500,115
20,21,NaN,NaN,NaN,4.0,3.0,3.0,NaN,604,N
21,22,NaN,NaN,NaN,7.0,3.0,4.0,99.4,603,290
22,23,NaN,NaN,NaN,7.0,2.0,5.0,97.68,508,210
23,24,NaN,NaN,Grade 10,8.0,1.0,5.0,NaN,511,183
24,25,NaN,NaN,NaN,6.0,2.0,5.0,66.26,504,132
25,26,NaN,NaN,NaN,6.0,4.0,2.0,85.29,505,150
26,27,NaN,NaN,NaN,6.0,5.0,5.0,14.23,503,104
27,28,NaN,NaN,NaN,5.0,1.0,4.0,80.27,509,165
28,29,NaN,NaN,NaN,8.0,3.0,5.0,87.4,600,185
29,30,NaN,NaN,NaN,8.0,3.0,3.0,72.37,510,165

In [10]:
spirit_cols = ["row_id","height_orig","social_media_use","age"]

df_spirit = df[spirit_cols].copy()

df_spirit.sample(30, random_state=42)

       row_id height_orig social_media_use  age
451       452         506              6.0  NaN
17161   17162         503              NaN  NaN
4269     4270         509              6.0  NaN
16583   16584         505              NaN  NaN
16325   16326         510              NaN  NaN
17420   17421         510              NaN  NaN
17843   17844         508              8.0  NaN
15888   15889         510              NaN  NaN
3351     3352         503              8.0  NaN
19505   19506         608              8.0  NaN
13496   13497         502              NaN  NaN
7020     7021         503              8.0  NaN
16027   16028         510              NaN  NaN
7468     7469         509              6.0  NaN
6373     6374         507              8.0  NaN
8403     8404         503              7.0  NaN
856       857         N N              NaN  NaN
15390   15391         510              NaN  NaN
18472   18473         NaN              6.0  NaN
13653   13654         501              NaN  NaN
13361   13362         510              NaN  NaN
18655   18656         600              6.0  NaN
19980   19981         601              1.0  NaN
8654     8655         504              6.0  NaN
18602   18603         411              8.0  NaN
6532     6533         600              4.0  NaN
7007     7008         506    always online  NaN
20011   20012         504              8.0  NaN
6556     6557         508              6.0  NaN
11764   11765         502              8.0  NaN

In [11]:
import pandas as pd
import numpy as np
from pathlib import Path

# Hitta projektmappen
project_folder = Path.cwd().parent if Path.cwd().name == "notebooks" else Path.cwd()

# Läs in det gemensamma dirty datasetet
df = pd.read_csv(project_folder / "data" / "dirty" / "yrbs_dirty_9vars.csv")

# Välj bara Spirits variabler
spirit_cols = ["row_id", "height_orig", "social_media_use", "age"]
df_spirit = df[spirit_cols].copy()

print("Shape:")
print(df_spirit.shape)

print("\nFörsta 20 raderna:")
display(df_spirit.head(20))

print("\n30 slumpmässiga rader:")
display(df_spirit.sample(30, random_state=42))

print("\nInfo:")
df_spirit.info()

print("\nMissing values:")
print(df_spirit.isnull().sum())

print("\nDubbletter:")
print(df_spirit.duplicated().sum())

print("\nVärden i age:")
print(df_spirit["age"].value_counts(dropna=False))

print("\nVärden i social_media_use:")
print(df_spirit["social_media_use"].value_counts(dropna=False))

print("\nVärden i height_orig:")
print(df_spirit["height_orig"].value_counts(dropna=False).head(30))

print("\nBeskrivning av height_orig:")
print(pd.to_numeric(df_spirit["height_orig"], errors="coerce").describe())

print("\nRader där age inte är numerisk eller saknas:")
display(df_spirit[
    pd.to_numeric(df_spirit["age"], errors="coerce").isna()
].head(30))

print("\nRader där social_media_use inte är numerisk eller saknas:")
display(df_spirit[
    pd.to_numeric(df_spirit["social_media_use"], errors="coerce").isna()
].head(30))

print("\nRader där height_orig inte är numerisk eller saknas:")
display(df_spirit[
    pd.to_numeric(df_spirit["height_orig"], errors="coerce").isna()
].head(30))

print("\nRader med möjliga extrema värden i height_orig:")
height_num = pd.to_numeric(df_spirit["height_orig"], errors="coerce")
display(df_spirit[(height_num > 800) | (height_num < 100)].head(30))

Shape:
(20118, 4)

Första 20 raderna:

    row_id height_orig social_media_use  age
0        1         505              6.0  NaN
1        2         N N              4.0  NaN
2        3         506              8.0  NaN
3        4         N N              8.0  NaN
4        5         601              6.0  NaN
5        6         511              8.0  NaN
6        7         600              8.0  NaN
7        8         500              6.0  NaN
8        9         505              6.0  NaN
9       10         504              6.0  NaN
10      11         507              1.0  NaN
11      12         502              6.0  NaN
12      13         506              6.0  NaN
13      14         504              6.0  NaN
14      15         509              7.0  NaN
15      16         506              8.0  NaN
16      17         602              8.0  NaN
17      18         604              3.0  NaN
18      19         505              6.0  NaN
19      20         500              2.0  NaN

30 slumpmässiga rader:

       row_id height_orig social_media_use  age
451       452         506              6.0  NaN
17161   17162         503              NaN  NaN
4269     4270         509              6.0  NaN
16583   16584         505              NaN  NaN
16325   16326         510              NaN  NaN
17420   17421         510              NaN  NaN
17843   17844         508              8.0  NaN
15888   15889         510              NaN  NaN
3351     3352         503              8.0  NaN
19505   19506         608              8.0  NaN
13496   13497         502              NaN  NaN
7020     7021         503              8.0  NaN
16027   16028         510              NaN  NaN
7468     7469         509              6.0  NaN
6373     6374         507              8.0  NaN
8403     8404         503              7.0  NaN
856       857         N N              NaN  NaN
15390   15391         510              NaN  NaN
18472   18473         NaN              6.0  NaN
13653   13654         501              NaN  NaN
13361   13362         510              NaN  NaN
18655   18656         600              6.0  NaN
19980   19981         601              1.0  NaN
8654     8655         504              6.0  NaN
18602   18603         411              8.0  NaN
6532     6533         600              4.0  NaN
7007     7008         506    always online  NaN
20011   20012         504              8.0  NaN
6556     6557         508              6.0  NaN
11764   11765         502              8.0  NaN

Info:
<class 'pandas.DataFrame'>
RangeIndex: 20118 entries, 0 to 20117
Data columns (total 4 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   row_id            20118 non-null  int64
 1   height_orig       19849 non-null  str
 2   social_media_use  15221 non-null  str
 3   age               10 non-null     str
dtypes: int64(1), str(3)
memory usage: 628.8 KB

Missing values:
row_id                  0
height_orig           269
social_media_use     4897
age                 20108
dtype: int64

Dubbletter:
15

Värden i age:
age
NaN        20108
sixteen       10
Name: count, dtype: int64

Värden i social_media_use:
social_media_use
6.0              5881
NaN              4897
8.0              4800
7.0              1183
1.0              1079
5.0               903
4.0               708
2.0               406
3.0               231
always online      10
1                  10
6                  10
Name: count, dtype: int64

Värden i height_orig:
height_orig
504    1686
506    1685
507    1634
505    1590
503    1552
508    1541
510    1367
509    1335
502    1256
511    1113
600    1084
501     747
601     575
500     513
602     437
N N     341
411     321
NaN     269
603     255
604     127
605      83
711      67
410      64
409      41
606      26
5        26
607      24
609      24
408      21
300      20
Name: count, dtype: int64

Beskrivning av height_orig:
count    19508.000000
mean       516.516609
std         51.544700
min          3.000000
25%        504.000000
50%        507.000000
75%        510.000000
max        999.000000
Name: height_orig, dtype: float64

Rader där age inte är numerisk eller saknas:

    row_id height_orig social_media_use  age
0        1         505              6.0  NaN
1        2         N N              4.0  NaN
2        3         506              8.0  NaN
3        4         N N              8.0  NaN
4        5         601              6.0  NaN
5        6         511              8.0  NaN
6        7         600              8.0  NaN
7        8         500              6.0  NaN
8        9         505              6.0  NaN
9       10         504              6.0  NaN
10      11         507              1.0  NaN
11      12         502              6.0  NaN
12      13         506              6.0  NaN
13      14         504              6.0  NaN
14      15         509              7.0  NaN
15      16         506              8.0  NaN
16      17         602              8.0  NaN
17      18         604              3.0  NaN
18      19         505              6.0  NaN
19      20         500              2.0  NaN
20      21         604              4.0  NaN
21      22         603              7.0  NaN
22      23         508              7.0  NaN
23      24         511              8.0  NaN
24      25         504              6.0  NaN
25      26         505              6.0  NaN
26      27         503              6.0  NaN
27      28         509              5.0  NaN
28      29         600              8.0  NaN
29      30         510              8.0  NaN

Rader där social_media_use inte är numerisk eller saknas:

     row_id height_orig social_media_use  age
32       33         510    always online  NaN
100     101         508              NaN  NaN
170     171         510              NaN  NaN
194     195         600              NaN  NaN
209     210         707              NaN  NaN
215     216         503              NaN  NaN
229     230         704              NaN  NaN
296     297         405              NaN  NaN
298     299         508              NaN  NaN
309     310         510              NaN  NaN
334     335         504              NaN  NaN
348     349         503              NaN  NaN
351     352         511              NaN  NaN
363     364         504              NaN  NaN
365     366         N N              NaN  NaN
380     381         505              NaN  NaN
483     484         509              NaN  NaN
491     492         510              NaN  NaN
526     527         508              NaN  NaN
537     538         505              NaN  NaN
539     540         700              NaN  NaN
547     548         509              NaN  NaN
550     551         507              NaN  NaN
554     555         504              NaN  NaN
560     561         500              NaN  NaN
563     564         507              NaN  NaN
571     572         509              NaN  NaN
587     588         510              NaN  NaN
596     597         503              NaN  NaN
602     603         511              NaN  NaN

Rader där height_orig inte är numerisk eller saknas:

     row_id height_orig social_media_use  age
1         2         N N              4.0  NaN
3         4         N N              8.0  NaN
172     173         N N              8.0  NaN
174     175         N N              1.0  NaN
279     280         N N              6.0  NaN
295     296         N N              8.0  NaN
335     336         N N              2.0  NaN
360     361         N N              6.0  NaN
365     366         N N              NaN  NaN
549     550         N N              8.0  NaN
603     604         N N              1.0  NaN
686     687         N N              8.0  NaN
697     698         N N              6.0  NaN
739     740         N N              2.0  NaN
756     757         N N              8.0  NaN
759     760         N N              8.0  NaN
849     850         N N              NaN  NaN
850     851         N N              NaN  NaN
851     852         N N              NaN  NaN
852     853         N N              NaN  NaN
853     854         N N              NaN  NaN
854     855         N N              1.0  NaN
855     856         N N              NaN  NaN
856     857         N N              NaN  NaN
857     858         N N              NaN  NaN
858     859         N N              NaN  NaN
859     860         N N              NaN  NaN
860     861         N N              NaN  NaN
861     862         N N              NaN  NaN
862     863         N N              NaN  NaN

Rader med möjliga extrema värden i height_orig:

       row_id height_orig social_media_use  age
1714     1715         999              8.0  NaN
3183     3184         999              NaN  NaN
7038     7039         999              2.0  NaN
9671     9672         999              1.0  NaN
11484   11485           5              6.0  NaN
11520   11521           5              8.0  NaN
11623   11624           7              1.0  NaN
11787   11788           5              4.0  NaN
11818   11819           5              6.0  NaN
11895   11896           5              1.0  NaN
12067   12068           6              1.0  NaN
13061   13062           6              1.0  NaN
13076   13077           5              8.0  NaN
13319   13320           5              NaN  NaN
13411   13412           5              NaN  NaN
13863   13864           6              NaN  NaN
13885   13886           5              NaN  NaN
13953   13954           7              NaN  NaN
13986   13987           6              NaN  NaN
14118   14119           5              NaN  NaN
14140   14141           7              NaN  NaN
14434   14435           5              NaN  NaN
14690   14691           6              NaN  NaN
14734   14735           5              NaN  NaN
15274   15275           5              NaN  NaN
15634   15635           5              NaN  NaN
15669   15670           6              NaN  NaN
16611   16612           6              NaN  NaN
16707   16708           6              NaN  NaN
16716   16717           3              NaN  NaN