In [3]:
import pandas as pd # jobba med tabeller/dataframes
import numpy as np # bland annat för NaN
from pathlib import Path # hitta rätt filväg till datasetet

In [7]:
# Gör att filvägen fungerar oavsett var notebooken körs ifrån
project_folder = Path.cwd().parent if Path.cwd().name == "notebooks" else Path.cwd()

# Läser in den smutsiga filen
df = pd.read_csv(project_folder / "data" / "dirty" / "yrbs_dirty_9vars.csv")

# skapar en mindre dataframa med mina 3 variabler
emmy_cols = ["row_id", "weight_orig", "mental_health_not_good", "grade"]
df_emmy = df[emmy_cols].copy()

# Shape - visar antal rader och kolumner
print(df_emmy.shape)

(20118, 4)

In [ ]:
# Upptäcka konstiga värden
display(df_emmy.head(20)) # head() visar början av datan
display(df_emmy.sample(30, random_state=42)) # sample() visar slumpmässiga rader, så vi inte bara ser toppen

    row_id weight_orig mental_health_not_good grade
0        1         180                    1.0   NaN
1        2         233                    3.0   NaN
2        3         165                    2.0   NaN
3        4         105                    3.0   NaN
4        5         125                    3.0   NaN
5        6         160                    NaN   NaN
6        7         165                    3.0   NaN
7        8         162                    2.0   NaN
8        9         135                    3.0   NaN
9       10         117                    1.0   NaN
10      11         140                    1.0   NaN
11      12         159                    1.0   NaN
12      13         145                    1.0   NaN
13      14         300                    1.0   NaN
14      15         163                    1.0   NaN
15      16         215                    4.0   NaN
16      17         270                    1.0   NaN
17      18         150                    3.0   NaN
18      19         110                    3.0   NaN
19      20         115                    3.0   NaN

       row_id weight_orig mental_health_not_good grade
451       452         150                    3.0   NaN
17161   17162         106                    2.0   NaN
4269     4270         156                    3.0   NaN
16583   16584         165                    1.0   NaN
16325   16326         140                    2.0   NaN
17420   17421         170                    1.0   NaN
17843   17844         160                    NaN   NaN
15888   15889         130                    2.0   NaN
3351     3352         211                    4.0   NaN
19505   19506         190                    NaN   NaN
13496   13497         120                    3.0   NaN
7020     7021         102                    4.0   NaN
16027   16028         136                    1.0   NaN
7468     7469         152                    1.0   NaN
6373     6374         165                    4.0   NaN
8403     8404         190                    5.0   NaN
856       857         165                    NaN   NaN
15390   15391         170                    2.0   NaN
18472   18473         NaN                    NaN   NaN
13653   13654         NaN                    4.0   NaN
13361   13362         130                    3.0   NaN
18655   18656         170                    NaN   NaN
19980   19981         142                    NaN   NaN
8654     8655         149                    4.0   NaN
18602   18603         130                    NaN   NaN
6532     6533         120                    2.0   NaN
7007     7008         121                      A   NaN
20011   20012         115                    NaN   NaN
6556     6557         150                    1.0   NaN
11764   11765         099                    NaN   NaN

In [12]:
# Visar antal värden, datatyper och hur många som inte är null
df_emmy.info()

<class 'pandas.DataFrame'>
RangeIndex: 20118 entries, 0 to 20117
Data columns (total 4 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   row_id                  20118 non-null  int64
 1   weight_orig             19434 non-null  str
 2   mental_health_not_good  15734 non-null  str
 3   grade                   30 non-null     str
dtypes: int64(1), str(3)
memory usage: 628.8 KB

In [ ]:
# Visar hur många riktiga saknade värden som redan finns
print(df_emmy.isnull().sum())

row_id                        0
weight_orig                 684
mental_health_not_good     4384
grade                     20088
dtype: int64
15

In [16]:
# Visar om det finns identiska rader
print(df_emmy.duplicated().sum())

15

In [17]:
# Extra viktigt - visar 'N', 'N N', tomma strängar, bokstäver i numeriska kolumner och ovanliga/extrema värden
print(df_emmy['grade'].value_counts(dropna=False))
print(df_emmy['mental_health_not_good'].value_counts(dropna=False))
print(df_emmy['weight_orig'].value_counts(dropna=False).head(30))

grade
NaN           20088
Grade 10         10
10th grade       10
2                10
Name: count, dtype: int64
mental_health_not_good
3.0        4744
NaN        4384
4.0        3376
2.0        3304
1.0        2837
5.0        1433
 always      10
A            10
5            10
Always       10
Name: count, dtype: int64
weight_orig
120    952
130    906
140    841
150    800
135    718
N      714
125    690
NaN    684
160    626
145    607
115    565
110    546
180    451
165    420
170    402
155    385
200    330
175    310
190    286
100    242
105    236
185    231
210    179
220    178
138    158
230    154
128    149
132    147
118    147
195    132
Name: count, dtype: int64

In [18]:
# Upptäcker orimliga värden
# Försöker göra om 'weight_orig' till siffror, det som inte går blir NaN, sedan får vi statistik som mean, min, max
print(pd.to_numeric(df_emmy['weight_orig'], errors='coerce').describe())

count    18716.000000
mean       151.985253
std         46.710393
min          0.000000
25%        122.000000
50%        141.000000
75%        170.000000
max        999.000000
Name: weight_orig, dtype: float64

In [ ]:
# Visar rader där 'grade' inte grå att läsa som siffra
display(df_emmy[
    pd.to_numeric(df_emmy['grade'], errors='coerce').isna()
].head(30))

    row_id weight_orig mental_health_not_good     grade
0        1         180                    1.0       NaN
1        2         233                    3.0       NaN
2        3         165                    2.0       NaN
3        4         105                    3.0       NaN
4        5         125                    3.0       NaN
5        6         160                    NaN       NaN
6        7         165                    3.0       NaN
7        8         162                    2.0       NaN
8        9         135                    3.0       NaN
9       10         117                    1.0       NaN
10      11         140                    1.0       NaN
11      12         159                    1.0       NaN
12      13         145                    1.0       NaN
13      14         300                    1.0       NaN
14      15         163                    1.0       NaN
15      16         215                    4.0       NaN
16      17         270                    1.0       NaN
17      18         150                    3.0       NaN
18      19         110                    3.0       NaN
19      20         115                    3.0       NaN
20      21           N                    3.0       NaN
21      22         290                    3.0       NaN
22      23         210                    2.0       NaN
23      24         183                    1.0  Grade 10
24      25         132                    2.0       NaN
25      26         150                    4.0       NaN
26      27         104                    5.0       NaN
27      28         165                    1.0       NaN
28      29         185                    3.0       NaN
29      30         165                    3.0       NaN

In [ ]:
# Visar rader där 'mental_health...' inte grå att läsa som siffra
display(df_emmy[
    pd.to_numeric(df_emmy['mental_health_not_good'], errors='coerce').isna()
].head(30))

     row_id weight_orig mental_health_not_good grade
5         6         160                    NaN   NaN
75       76         200                    NaN   NaN
100     101         155                    NaN   NaN
153     154         150                    NaN   NaN
170     171         238                    NaN   NaN
209     210          61                    NaN   NaN
215     216         190                    NaN   NaN
216     217           N                    NaN   NaN
229     230          50                    NaN   NaN
255     256         140                    NaN   NaN
274     275         122                    NaN   NaN
289     290           N                    NaN   NaN
296     297           N                    NaN   NaN
298     299         159                    NaN   NaN
303     304           N                    NaN   NaN
309     310         186                    NaN   NaN
310     311         197                    NaN   NaN
328     329         160                    NaN   NaN
334     335           N                    NaN   NaN
348     349           N                    NaN   NaN
351     352         205                    NaN   NaN
363     364         139                    NaN   NaN
365     366           N                    NaN   NaN
380     381         208                    NaN   NaN
385     386         137                    NaN   NaN
483     484         152                    NaN   NaN
491     492         152                    NaN   NaN
526     527         173                    NaN   NaN
530     531         175                    NaN   NaN
537     538         115                    NaN   NaN

In [23]:
# Visar rader där 'weight_orig' inte grå att läsa som siffra
display(df_emmy[
    pd.to_numeric(df_emmy['weight_orig'], errors='coerce').isna()
].head(30))

     row_id weight_orig mental_health_not_good grade
20       21           N                    3.0   NaN
96       97           N                    4.0   NaN
144     145           N                    1.0   NaN
174     175           N                    2.0   NaN
181     182           N                    1.0   NaN
216     217           N                    NaN   NaN
279     280           N                    3.0   NaN
280     281           N                    2.0   NaN
283     284           N                    2.0   NaN
289     290           N                    NaN   NaN
295     296           N                    3.0   NaN
296     297           N                    NaN   NaN
303     304           N                    NaN   NaN
313     314           N                    4.0   NaN
334     335           N                    NaN   NaN
335     336           N                    3.0   NaN
348     349           N                    NaN   NaN
349     350           N                    4.0   NaN
360     361           N                    4.0   NaN
364     365           N                    3.0   NaN
365     366           N                    NaN   NaN
433     434           N                    2.0   NaN
462     463           N                    3.0   NaN
485     486           N                    4.0   NaN
494     495           N                    3.0   NaN
522     523           N                    1.0   NaN
540     541           N                    3.0   NaN
547     548           N                    1.0   NaN
554     555           N                    NaN   NaN
560     561           N                    NaN   NaN

In [24]:
# Kollar om vikten verkar orimlig. Gränserna 400-50 hjälper oss hitta misstänkta värden
weight_num = pd.to_numeric(df_emmy['weight_orig'], errors='coerce')
display(df_emmy[(weight_num > 400) | (weight_num < 50)].head(30))

       row_id weight_orig mental_health_not_good grade
1098     1099          48                    1.0   NaN
1755     1756         999                    2.0   NaN
1756     1757         999                    2.0   NaN
2116     2117          45                    1.0   NaN
2452     2453          34                    1.0   NaN
2886     2887          26                    1.0   NaN
5039     5040          32                    NaN   NaN
7370     7371          45                    3.0   NaN
8165     8166         999                    1.0   NaN
9239     9240          25                    4.0   NaN
9257     9258          25                    3.0   NaN
9474     9475          37                    2.0   NaN
9479     9480          32                    5.0   NaN
9590     9591          47                    2.0   NaN
11584   11585         000                    NaN   NaN
11623   11624         001                    NaN   NaN
11718   11719         000                    NaN   NaN
12354   12355           1                    NaN   NaN
12454   12455         000                    3.0   NaN
12769   12770           5                 always   NaN
12801   12802           1                    1.0   NaN
12805   12806           9                    3.0   NaN
12868   12869          03                    1.0   NaN
12998   12999          25                    3.0   NaN
13180   13181          13                    NaN   NaN
13183   13184         025                    4.0   NaN
13281   13282          14                    NaN   NaN
13283   13284           5                    4.0   NaN
13381   13382         999                    3.0   NaN
13431   13432         010                    4.0   NaN

In [ ]:
# df_clean = fixad data
df_clean = df_emmy.copy()

In [26]:
df_clean = df_clean.replace(['', ' ', 'N', 'N N'], np.nan)

In [27]:
df_clean['weight_orig'] = pd.to_numeric(df_clean['weight_orig'], errors='coerce')
df_clean['mental_health_not_good'] = pd.to_numeric(df_clean['mental_health_not_good'], errors='coerce')
df_clean['grade'] = pd.to_numeric(df_clean['grade'], errors='coerce')

In [28]:
df_clean.loc[~df_clean['weight_orig'].between(50, 400), 'weight_orig'] = np.nan

In [29]:
df_clean.info()
df_clean.isnull().sum()

<class 'pandas.DataFrame'>
RangeIndex: 20118 entries, 0 to 20117
Data columns (total 4 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   row_id                  20118 non-null  int64
 1   weight_orig             18638 non-null  float64
 2   mental_health_not_good  15704 non-null  float64
 3   grade                   10 non-null     float64
dtypes: float64(3), int64(1)
memory usage: 628.8 KB

row_id                        0
weight_orig                1480
mental_health_not_good     4414
grade                     20108
dtype: int64

In [ ]:
print('Före rensning:')
print(df_emmy.info())

print('\nEfter rensning:')
print(df_clean.info())