In [1]:
import pandas as pd
import numpy as np
from pathlib import Path

In [2]:
["bmipct", "sex", "sleep_hours"]

['bmipct', 'sex', 'sleep_hours']

In [3]:
project_folder = Path.cwd().parent if Path.cwd().name == "notebooks" else Path.cwd()

In [4]:
df = pd.read_csv(project_folder / "data" / "dirty" / "yrbs_dirty_9vars.csv")

In [5]:
mahtab_cols = ["row_id", "bmipct", "sex", "sleep_hours"]
df_mahtab = df[mahtab_cols].copy()

print("Shape:")
print(df_mahtab.shape)

print("\nFörsta 20 raderna:")
display(df_mahtab.head(20))

print("\n30 slumpmässiga rader:")
display(df_mahtab.sample(30, random_state=42))

print("\nInfo:")
df_mahtab.info()

print("\nMissing values:")
print(df_mahtab.isnull().sum())

print("\nDubbletter:")
print(df_mahtab.duplicated().sum())

print("\nVärden i sex:")
print(df_mahtab["sex"].value_counts(dropna=False))

print("\nVärden i sleep_hours:")
print(df_mahtab["sleep_hours"].value_counts(dropna=False))

print("\nVärden i bmipct:")
print(df_mahtab["bmipct"].value_counts(dropna=False).head(30))

print("\nBeskrivning av bmipct:")
print(pd.to_numeric(df_mahtab["bmipct"], errors="coerce").describe())

print("\nRader där sex inte är numerisk eller saknas:")
display(df_mahtab[
    pd.to_numeric(df_mahtab["sex"], errors="coerce").isna()
].head(30))

print("\nRader där sleep_hours inte är numerisk eller saknas:")
display(df_mahtab[
    pd.to_numeric(df_mahtab["sleep_hours"], errors="coerce").isna()
].head(30))

print("\nRader där bmipct inte är numerisk eller saknas:")
display(df_mahtab[
    pd.to_numeric(df_mahtab["bmipct"], errors="coerce").isna()
].head(30))

print("\nRader med möjliga extrema värden i bmipct:")
bmipct_num = pd.to_numeric(df_mahtab["bmipct"], errors="coerce")
display(df_mahtab[(bmipct_num > 100) | (bmipct_num < 0)].head(30))

Shape:
(20118, 4)

Första 20 raderna:

    row_id bmipct  sex sleep_hours
0        1  97.08  NaN         3.0
1        2    NaN  NaN         5.0
2        3  92.26  NaN         1.0
3        4    NaN  NaN         4.0
4        5   7.57  NaN         3.0
5        6  68.89  NaN         2.0
6        7  60.48  NaN         2.0
7        8  97.53  NaN         1.0
8        9  76.45  NaN         1.0
9       10  34.79  NaN         2.0
10      11  64.23  NaN         7.0
11      12  95.81  NaN         4.0
12      13  82.18  NaN         4.0
13      14  99.42  NaN         2.0
14      15  86.65  NaN         5.0
15      16  98.75  NaN         2.0
16      17  99.19  NaN         3.0
17      18   3.87  NaN         5.0
18      19  17.75  NaN         5.0
19      20    NaN  NaN         1.0

30 slumpmässiga rader:

       row_id bmipct  sex sleep_hours
451       452  75.84  NaN         3.0
17161   17162   30.3  NaN         NaN
4269     4270  74.76  NaN         2.0
16583   16584  94.34  NaN         3.0
16325   16326   58.1  NaN         NaN
17420   17421  79.37  NaN         4.0
17843   17844  87.13  NaN         NaN
15888   15889  25.66  NaN         NaN
3351     3352  99.18  NaN         2.0
19505   19506  40.84  NaN         4.0
13496   13497  66.09  NaN         3.0
7020     7021  10.54  NaN         3.0
16027   16028  49.89  NaN         4.0
7468     7469  70.03  NaN         NaN
6373     6374  90.32  NaN         4.0
8403     8404  97.88  NaN         NaN
856       857    NaN  NaN         NaN
15390   15391   87.5  NaN         4.0
18472   18473    NaN  NaN         4.0
13653   13654    NaN  NaN         3.0
13361   13362   36.2  NaN         4.0
18655   18656  74.74  NaN         6.0
19980   19981   39.6  NaN         4.0
8654     8655  83.17  NaN         2.0
18602   18603   91.1  NaN         6.0
6532     6533   0.24  NaN         7.0
7007     7008  49.55  NaN         2.0
20011   20012  42.53  NaN         5.0
6556     6557  78.32  NaN         5.0
11764   11765   9.19  NaN         NaN

Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20118 entries, 0 to 20117
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   row_id       20118 non-null  int64
 1   bmipct       16938 non-null  object
 2   sex          30 non-null     object
 3   sleep_hours  16573 non-null  object
dtypes: int64(1), object(3)
memory usage: 628.8+ KB

Missing values:
row_id             0
bmipct          3180
sex            20088
sleep_hours     3545
dtype: int64

Dubbletter:
15

Värden i sex:
sex
NaN      20088
M           10
Male        10
 male       10
Name: count, dtype: int64

Värden i sleep_hours:
sleep_hours
4.0    4614
3.0    4128
NaN    3545
5.0    2863
2.0    2435
1.0    1575
6.0     704
7.0     244
ten      10
Name: count, dtype: int64

Värden i bmipct:
bmipct
NaN      3180
47.58      35
70.84      33
40.55      33
67.0       31
62.96      29
47.28      29
0.0        29
30.7       29
53.97      28
29.93      26
57.32      26
42.53      25
66.09      24
78.01      24
62.39      24
48.82      23
42.91      23
98.28      23
69.91      23
56.13      23
71.41      23
52.56      23
62.19      23
47.96      22
48.32      22
46.08      22
96.6       22
61.88      22
29.09      22
Name: count, dtype: int64

Beskrivning av bmipct:
count    16928.000000
mean        63.670816
std         33.420819
min          0.000000
25%         41.490000
50%         68.840000
75%         90.250000
max        999.000000
Name: bmipct, dtype: float64

Rader där sex inte är numerisk eller saknas:

    row_id bmipct  sex sleep_hours
0        1  97.08  NaN         3.0
1        2    NaN  NaN         5.0
2        3  92.26  NaN         1.0
3        4    NaN  NaN         4.0
4        5   7.57  NaN         3.0
5        6  68.89  NaN         2.0
6        7  60.48  NaN         2.0
7        8  97.53  NaN         1.0
8        9  76.45  NaN         1.0
9       10  34.79  NaN         2.0
10      11  64.23  NaN         7.0
11      12  95.81  NaN         4.0
12      13  82.18  NaN         4.0
13      14  99.42  NaN         2.0
14      15  86.65  NaN         5.0
15      16  98.75  NaN         2.0
16      17  99.19  NaN         3.0
17      18   3.87  NaN         5.0
18      19  17.75  NaN         5.0
19      20    NaN  NaN         1.0
20      21    NaN  NaN         3.0
21      22   99.4  NaN         4.0
22      23  97.68  NaN         5.0
23      24    NaN  NaN         5.0
24      25  66.26  NaN         5.0
25      26  85.29  NaN         2.0
26      27  14.23  NaN         5.0
27      28  80.27  NaN         4.0
28      29   87.4  NaN         5.0
29      30  72.37  NaN         3.0

Rader där sleep_hours inte är numerisk eller saknas:

     row_id bmipct  sex sleep_hours
75       76    NaN  NaN         NaN
94       95   36.8  NaN         NaN
98       99  86.29  NaN         NaN
100     101  65.99  NaN         NaN
103     104  73.72  NaN         NaN
127     128   97.9  NaN         NaN
130     131  39.92  NaN         NaN
147     148   7.15  NaN         NaN
150     151  42.13  NaN         NaN
152     153  95.61  NaN         NaN
166     167  93.85  NaN         NaN
168     169   27.6  NaN         NaN
170     171  99.15  NaN         NaN
173     174  41.27  NaN         NaN
175     176    NaN  NaN         NaN
196     197  47.58  NaN         NaN
209     210    NaN  NaN         NaN
215     216   97.5  NaN         NaN
216     217    NaN  NaN         NaN
220     221  88.44  NaN         NaN
228     229  26.69  NaN         NaN
229     230    NaN  NaN         NaN
233     234    NaN  NaN         NaN
234     235   98.5  NaN         NaN
251     252  69.87  NaN         NaN
255     256  57.76  NaN         NaN
274     275  70.67  NaN         NaN
277     278  46.48  NaN         NaN
296     297    NaN  NaN         NaN
298     299    NaN  NaN         NaN

Rader där bmipct inte är numerisk eller saknas:

     row_id bmipct  sex sleep_hours
1         2    NaN  NaN         5.0
3         4    NaN  NaN         4.0
19       20    NaN  NaN         1.0
20       21    NaN  NaN         3.0
23       24    NaN  NaN         5.0
41       42    NaN  NaN         5.0
56       57    NaN  NaN         3.0
59       60    NaN  NaN         1.0
65       66    NaN  NaN         4.0
75       76    NaN  NaN         NaN
78       79    NaN  NaN         1.0
86       87    NaN  NaN         6.0
87       88    NaN  NaN         4.0
96       97    NaN  NaN         4.0
99      100    NaN  NaN         2.0
141     142    NaN  NaN         1.0
144     145    NaN  NaN         1.0
146     147    NaN  NaN         1.0
172     173    NaN  NaN         1.0
174     175    NaN  NaN         6.0
175     176    NaN  NaN         NaN
181     182    NaN  NaN         6.0
183     184    NaN  NaN         6.0
186     187    NaN  NaN         5.0
200     201    NaN  NaN         5.0
209     210    NaN  NaN         NaN
216     217    NaN  NaN         NaN
223     224    NaN  NaN         4.0
225     226    NaN  NaN         5.0
229     230    NaN  NaN         NaN

Rader med möjliga extrema värden i bmipct:

       row_id bmipct  sex sleep_hours
2671     2672    999  NaN         3.0
8250     8251    999  NaN         4.0
9647     9648    999  NaN         1.0
10785   10786    999  NaN         1.0
13339   13340    999  NaN         2.0